#########################################################
#
# Owned and copyright BitBlaze, 2007. All rights reserved.
#
#########################################################

export OCAMLMAKEFILE=OCamlMakefile

SOURCES=libstp_regerrorhandler.c libstp.idl stpvc.ml stpvc.mli 
RESULT=stpvc

LIBDIRS = ..
CLIBS = stp stdc++

all: dcl ncl top

include $(OCAMLMAKEFILE)
