; RUN: %solver %s | %OutputCheck %s
; CHECK: ^sat
;
; Regression test for RemoveUnconstrained over an n-ary bvmul whose
; operands repeat.  (bvmul (select a #b...1) (select a #b...0) (select a #b...0))
; has every operand unconstrained, so RemoveUnconstrained rewrites the
; product to a fresh variable and drives the other operands to 1.  The two
; occurrences of (select a #x0000) resolve to the same fresh symbol, and the
; substitution loop replaced it once per position.  The second replace()
; re-entered the substitution map for an already-substituted variable and
; aborted with
;   Assertion `!InsideSubstitutionMap(e0) && "e0 MUST NOT be in the SolverMap"'
; The loop must substitute each distinct operand at most once.
;
; Reduced (via ddSMT) from a QF_ABV benchmark generated by FuzzSMT.
(set-logic QF_ABV)
(declare-fun a2 () (Array (_ BitVec 8) (_ BitVec 13)))
(declare-fun a () (Array (_ BitVec 16) (_ BitVec 7)))
(assert (not (= (select a2 ((_ zero_extend 1) (select a (_ bv0 16))))
                ((_ sign_extend 6) (bvmul (select a (_ bv1 16))
                                          (select a (_ bv0 16))
                                          (select a (_ bv0 16)))))))
(check-sat)
