// Stable FP rule schema identifiers and their metadata.
// Intentionally no include guard: include with FP_RULE defined.
// Symmetric instantiations share an ID. Never reuse a retired ID for a different schema.
// Fields: enum token, ID, operations, family, verification group, additional
// selection conditions (all displayed operand/mode guards still apply).
// Finite verification groups are NOT proof certificates: a group names the tests
// that check a schema at explicit formats and modes, not a proof for every format.
FP_RULE(MUL_S1, "MUL-S1", "mul", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(MUL_S2, "MUL-S2", "mul", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(MUL_S3, "MUL-S3", "mul", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(MUL_S4, "MUL-S4", "mul", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(MUL_S5, "MUL-S5", "mul", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(MUL_S6, "MUL-S6", "mul", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(MUL_S7, "MUL-S7", "mul", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(MUL_O1, "MUL-O1", "mul", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(MUL_O2, "MUL-O2", "mul", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(MUL_O1y, "MUL-O1y", "mul", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(MUL_O2y, "MUL-O2y", "mul", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(MUL_B1, "MUL-B1", "mul", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(MUL_B2, "MUL-B2", "mul", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(MUL_B3, "MUL-B3", "mul", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(MUL_B4, "MUL-B4", "mul", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(MUL_B5, "MUL-B5", "mul", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(MUL_F1, "MUL-F1", "mul", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(MUL_F2, "MUL-F2", "mul", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(MUL_P1, "MUL-P1", "mul", "initial", "bands", "eb,p>=2; displayed operand and mode guards; 2<=k and 2k+1<=p")
FP_RULE(MUL_I1, "MUL-I1", "mul", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(MUL_I2, "MUL-I2", "mul", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(MUL_I3, "MUL-I3", "mul", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(DIV_S1, "DIV-S1", "div", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(DIV_S2, "DIV-S2", "div", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(DIV_S3, "DIV-S3", "div", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(DIV_S4, "DIV-S4", "div", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(DIV_S5u, "DIV-S5u", "div", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(DIV_S5, "DIV-S5", "div", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards; 2^(eb-1)>=p")
FP_RULE(DIV_S6, "DIV-S6", "div", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(DIV_S7, "DIV-S7", "div", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(DIV_O1, "DIV-O1", "div", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(DIV_O2, "DIV-O2", "div", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(DIV_B1, "DIV-B1", "div", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(DIV_B2, "DIV-B2", "div", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(DIV_B3, "DIV-B3", "div", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(DIV_B3b, "DIV-B3b", "div", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(DIV_B4, "DIV-B4", "div", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(DIV_B5, "DIV-B5", "div", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(DIV_B6, "DIV-B6", "div", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(DIV_F1, "DIV-F1", "div", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(DIV_F2, "DIV-F2", "div", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(DIV_P1, "DIV-P1", "div", "initial", "bands", "eb,p>=2; displayed operand and mode guards; 2<=k and 2k+1<=p")
FP_RULE(DIV_I1, "DIV-I1", "div", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(DIV_I2, "DIV-I2", "div", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(DIV_I3, "DIV-I3", "div", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(DIV_I4, "DIV-I4", "div", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(DIV_I5, "DIV-I5", "div", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(SQRT_S1, "SQRT-S1", "sqrt", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(SQRT_S2, "SQRT-S2", "sqrt", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(SQRT_S3, "SQRT-S3", "sqrt", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(SQRT_S4, "SQRT-S4", "sqrt", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(SQRT_S6, "SQRT-S6", "sqrt", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(SQRT_S7, "SQRT-S7", "sqrt", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards; 2^(eb-1)>=p+1")
FP_RULE(SQRT_S8, "SQRT-S8", "sqrt", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(SQRT_O1, "SQRT-O1", "sqrt", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(SQRT_O2, "SQRT-O2", "sqrt", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(SQRT_B1, "SQRT-B1", "sqrt", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(SQRT_B2, "SQRT-B2", "sqrt", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(SQRT_P1, "SQRT-P1", "sqrt", "initial", "bands", "eb,p>=2; displayed operand and mode guards; 2<=k and 2k+1<=p")
FP_RULE(SQRT_I1, "SQRT-I1", "sqrt", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(SQRT_I2, "SQRT-I2", "sqrt", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(ADD_S1, "ADD-S1", "add,sub", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(ADD_S2, "ADD-S2", "add,sub", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(ADD_S3, "ADD-S3", "add,sub", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(ADD_S3b, "ADD-S3b", "add,sub", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(ADD_S4, "ADD-S4", "add,sub", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(ADD_S5, "ADD-S5", "add,sub", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(ADD_S6, "ADD-S6", "add,sub", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(ADD_S7, "ADD-S7", "add,sub", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(ADD_S8, "ADD-S8", "add,sub", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(ADD_S9, "ADD-S9", "add,sub", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(ADD_M1, "ADD-M1", "add,sub", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(ADD_M2, "ADD-M2", "add,sub", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(ADD_M1x, "ADD-M1x", "add,sub", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(ADD_M2x, "ADD-M2x", "add,sub", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(ADD_B1, "ADD-B1", "add,sub", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(ADD_B2, "ADD-B2", "add,sub", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(ADD_B3, "ADD-B3", "add,sub", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(ADD_B4, "ADD-B4", "add,sub", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(ADD_B5, "ADD-B5", "add,sub", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(ADD_B6, "ADD-B6", "add,sub", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(ADD_B7, "ADD-B7", "add,sub", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(ADD_B8, "ADD-B8", "add,sub", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(ADD_A1, "ADD-A1", "add,sub", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(ADD_A2, "ADD-A2", "add,sub", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(ADD_A3, "ADD-A3", "add,sub", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(FMA_S1, "FMA-S1", "fma", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(FMA_S2, "FMA-S2", "fma", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(FMA_S3, "FMA-S3", "fma", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(FMA_S4, "FMA-S4", "fma", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(FMA_S5, "FMA-S5", "fma", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(FMA_S6, "FMA-S6", "fma", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(FMA_S7, "FMA-S7", "fma", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(FMA_S8, "FMA-S8", "fma", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(FMA_S9, "FMA-S9", "fma", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(FMA_M1, "FMA-M1", "fma", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(FMA_M2, "FMA-M2", "fma", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(FMA_B1, "FMA-B1", "fma", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(FMA_B2, "FMA-B2", "fma", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(FMA_B3, "FMA-B3", "fma", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(REM_S1, "REM-S1", "rem", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(REM_S2, "REM-S2", "rem", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(REM_S3, "REM-S3", "rem", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(REM_S4, "REM-S4", "rem", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(REM_S5, "REM-S5", "rem", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(REM_O1, "REM-O1", "rem", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(REM_O2, "REM-O2", "rem", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(REM_O3, "REM-O3", "rem", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(REM_O4, "REM-O4", "rem", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(REM_I1, "REM-I1", "rem", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(RTI_N1, "RTI-N1", "rti", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(RTI_N2, "RTI-N2", "rti", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards; 2^(eb-1)>=p")
FP_RULE(RTI_N3, "RTI-N3", "rti", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards; 2^(eb-1)<p")
FP_RULE(RTI_N4, "RTI-N4", "rti", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards; 2^(eb-1)<p")
FP_RULE(RTI_S1, "RTI-S1", "rti", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(RTI_S2, "RTI-S2", "rti", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(RTI_N5, "RTI-N5", "rti", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(RTI_O1p, "RTI-O1p", "rti", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(RTI_O1n, "RTI-O1n", "rti", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(RTI_O1z, "RTI-O1z", "rti", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(RTI_S3, "RTI-S3", "rti", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(RTI_B1, "RTI-B1", "rti", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(RTI_B2, "RTI-B2", "rti", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(RTI_B3, "RTI-B3", "rti", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(RTI_S4, "RTI-S4", "rti", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(RTI_I1, "RTI-I1", "rti", "initial", "arithmetic", "eb,p>=2; displayed operand and mode guards")
FP_RULE(CVT_S1, "CVT-S1", "to_sbv,to_ubv", "initial", "conversions", "eb,p>=2; displayed operand and mode guards; m>=2")
FP_RULE(CVT_S2, "CVT-S2", "to_sbv,to_ubv", "initial", "conversions", "eb,p>=2; displayed operand and mode guards; m>=2")
FP_RULE(CVT_S3, "CVT-S3", "to_sbv,to_ubv", "initial", "conversions", "eb,p>=2; displayed operand and mode guards; m>=2")
FP_RULE(CVT_B1, "CVT-B1", "to_sbv,to_ubv", "initial", "conversions", "eb,p>=2; displayed operand and mode guards; m>=2")
FP_RULE(UBV_B2, "UBV-B2", "to_ubv", "initial", "conversions", "eb,p>=2; displayed operand and mode guards; m>=2")
FP_RULE(SBV_B2, "SBV-B2", "to_sbv", "initial", "conversions", "eb,p>=2; displayed operand and mode guards; m>=2")
FP_RULE(SBV_B3, "SBV-B3", "to_sbv", "initial", "conversions", "eb,p>=2; displayed operand and mode guards; m>=2")
FP_RULE(SBV_B4, "SBV-B4", "to_sbv", "initial", "conversions", "eb,p>=2; displayed operand and mode guards; m>=2; p>m")
FP_RULE(SBV_B5, "SBV-B5", "to_sbv", "initial", "conversions", "eb,p>=2; displayed operand and mode guards; m>=2; m<=64; p>m")
FP_RULE(SBV_B6, "SBV-B6", "to_sbv", "initial", "conversions", "eb,p>=2; displayed operand and mode guards; m>=2; m<=64")
FP_RULE(UBV_B3, "UBV-B3", "to_ubv", "initial", "conversions", "eb,p>=2; displayed operand and mode guards; m>=2; m<=64")
FP_RULE(SBV_B7, "SBV-B7", "to_sbv", "initial", "conversions", "eb,p>=2; displayed operand and mode guards; m>=2; m<=64")
FP_RULE(UBV_B4, "UBV-B4", "to_ubv", "initial", "conversions", "eb,p>=2; displayed operand and mode guards; m>=2; 4<=m<=64")
FP_RULE(UBV_B5, "UBV-B5", "to_ubv", "initial", "conversions", "eb,p>=2; displayed operand and mode guards; m>=2")
FP_RULE(UBV_B6, "UBV-B6", "to_ubv", "initial", "conversions", "eb,p>=2; displayed operand and mode guards; m>=2")
FP_RULE(SBV_B8, "SBV-B8", "to_sbv", "initial", "conversions", "eb,p>=2; displayed operand and mode guards; m>=2; 4<=m<=64")
FP_RULE(SBV_B9, "SBV-B9", "to_sbv", "initial", "conversions", "eb,p>=2; displayed operand and mode guards; m>=2; 4<=m<=64")
FP_RULE(FMA_C1, "FMA-C1", "fma,mul,add", "cross", "cross", "eb,p>=2; partner applications share operands, format and mode; displayed guards")
FP_RULE(FMA_C2, "FMA-C2", "fma,mul,add", "cross", "cross", "eb,p>=2; partner applications share operands, format and mode; displayed guards")
FP_RULE(FMA_C3, "FMA-C3", "fma,mul,add", "cross", "cross", "eb,p>=2; partner applications share operands, format and mode; displayed guards")
FP_RULE(FMA_C4, "FMA-C4", "fma,mul,add", "cross", "cross", "eb,p>=2; partner applications share operands, format and mode; displayed guards")
FP_RULE(FMA_C5, "FMA-C5", "fma,mul,add", "cross", "cross", "eb,p>=2; partner applications share operands, format and mode; displayed guards")
FP_RULE(MUL_X2, "MUL-X2", "mul", "shape", "shapes", "eb,p>=2; integer lattice thresholds; displayed finiteness and no-overflow guards")
FP_RULE(ADD_X1, "ADD-X1", "add,sub", "shape", "shapes", "eb,p>=2; integer lattice thresholds; displayed finiteness and no-overflow guards")
FP_RULE(REM_X1, "REM-X1", "rem", "shape", "shapes", "eb,p>=2; integer lattice thresholds; displayed finiteness and no-overflow guards")
FP_RULE(FMA_X1, "FMA-X1", "fma", "shape", "shapes", "eb,p>=2; integer lattice thresholds; displayed finiteness and no-overflow guards")
FP_RULE(REL_C1, "REL-C1", "mul,div,sqrt,add,sub,fma,rem,rti", "relational", "congruence", "eb,p>=2; same operation, format and mode; displayed equality, sign and non-NaN guards")
FP_RULE(REL_U1, "REL-U1", "sqrt,rti", "relational", "relational", "eb,p>=2; same operation, format and mode; displayed equality, sign and non-NaN guards")
FP_RULE(REL_A1, "REL-A1", "add", "relational", "relational", "eb,p>=2; same operation, format and mode; displayed equality, sign and non-NaN guards")
FP_RULE(REL_M1, "REL-M1", "mul", "relational", "relational", "eb,p>=2; same operation, format and mode; displayed equality, sign and non-NaN guards")
FP_RULE(REL_S1, "REL-S1", "sub", "relational", "relational", "eb,p>=2; same operation, format and mode; displayed equality, sign and non-NaN guards")
FP_RULE(REL_S2, "REL-S2", "sub", "relational", "relational", "eb,p>=2; same operation, format and mode; displayed equality, sign and non-NaN guards")
FP_RULE(REL_D1, "REL-D1", "div", "relational", "relational", "eb,p>=2; same operation, format and mode; displayed equality, sign and non-NaN guards")
FP_RULE(REL_D2, "REL-D2", "div", "relational", "relational", "eb,p>=2; same operation, format and mode; displayed equality, sign and non-NaN guards")
FP_RULE(REL_F1, "REL-F1", "fma", "relational", "relational", "eb,p>=2; same operation, format and mode; displayed equality, sign and non-NaN guards")
FP_RULE(REL_F2, "REL-F2", "fma", "relational", "relational", "eb,p>=2; same operation, format and mode; displayed equality, sign and non-NaN guards")
FP_RULE(REF_V1, "REF-V1", "all admitted operations", "value", "value", "complete argument tuple; exact available evaluation; host equality convention")
FP_RULE(REF_B1, "REF-B1", "mul,div,sqrt,add,sub,fma,rti", "box", "boxes", "k<p-1; finite operands; domain restrictions and common-sign finite nonzero corner results; result prefix length>=1+eb+8")
FP_RULE(REF_E1, "REF-E1", "all admitted operations", "release", "release", "exact backend supports the operation; complete argument tuple; host equality convention")
FP_RULE(ACC_R1, "ACC-R1", "original source query", "acceptance", "repair", "exact source-formula replay accepts the original interpretation, including U")
