; RUN: %solver %s | %OutputCheck %s
; CHECK: ^sat
;
; Regression test for counterexample construction over a partial
; floating-point operation.  An out-of-range (_ fp.to_ubv 32) has no
; specified result, so totalising gives it the value of an unconstrained
; internal array read.  Here that value is stored into an array and read
; back through an array-content-dependent index, so building the model
; has to materialise the stored value.  Doing so used to hand the
; unconstrained array read to the bit-vector constant evaluator (reached
; through the bvsub that lowers to bvneg); the evaluator cannot read
; arrays and aborted with
;   Fatal Error: BVConstEvaluator: term is not a constant-term
; It must instead resolve the unconstrained read to a concrete value.
;
; Reduced (flattened to a single check-sat) from an industrial QF_ABVFP
; benchmark generated by VectorCAST, CC-BY-4.0.
(set-logic QF_ABVFP)
(declare-fun G6S8ODQ1ZX () (_ BitVec 32))
(declare-fun GOH2AHTA2P () (_ BitVec 32))
(declare-fun IAXWI81M0B () (Array (_ BitVec 32) (_ BitVec 32)))
(declare-fun EQQ1SQY2AQ () Bool)
(assert (let ((a!1 (bvnot ((_ extract 32 32)
                    (bvadd ((_ zero_extend 1) #x00000401)
                           ((_ zero_extend 1) #x00000401)))))
      (a!2 (fp.div roundTowardPositive
                   ((_ to_fp_unsigned 8 24)
                     roundTowardPositive
                     (bvsub (select IAXWI81M0B #x00000400) GOH2AHTA2P))
                   (fp #b0 #x7b #b10011001100110011001101))))
(let ((a!3 (distinct (fp.mul roundTowardPositive
                             a!2
                             (fp.div roundTowardPositive
                                     ((_ to_fp_unsigned 8 24)
                                       roundTowardPositive
                                       G6S8ODQ1ZX)
                                     (fp #b0 #x9c #b11011100110101100101000)))
                     (_ NaN 8 24)))
      (a!4 (distinct (fp.mul roundTowardPositive
                             a!2
                             (fp.div roundTowardPositive
                                     ((_ to_fp_unsigned 8 24)
                                       roundTowardPositive
                                       G6S8ODQ1ZX)
                                     (fp #b0 #x9c #b11011100110101100101000)))
                     (_ +oo 8 24)))
      (a!5 (distinct (fp.mul roundTowardPositive
                             a!2
                             (fp.div roundTowardPositive
                                     ((_ to_fp_unsigned 8 24)
                                       roundTowardPositive
                                       G6S8ODQ1ZX)
                                     (fp #b0 #x9c #b11011100110101100101000)))
                     (_ -oo 8 24)))
      (a!6 (fp.geq (fp.mul roundTowardPositive
                           a!2
                           (fp.div roundTowardPositive
                                   ((_ to_fp_unsigned 8 24)
                                     roundTowardPositive
                                     G6S8ODQ1ZX)
                                   (fp #b0 #x9c #b11011100110101100101000)))
                   (_ +zero 8 24)))
      (a!7 (fp.leq (fp.mul roundTowardPositive
                           a!2
                           (fp.div roundTowardPositive
                                   ((_ to_fp_unsigned 8 24)
                                     roundTowardPositive
                                     G6S8ODQ1ZX)
                                   (fp #b0 #x9c #b11011100110101100101000)))
                   (fp #b0 #x9f #b00000000000000000000000))))
  (and (distinct a!1 #b0) a!3 a!4 a!5 a!6 a!7 (distinct a!1 #b0)))))
(assert (let ((a!1 (bvnot ((_ extract 32 32)
                    (bvadd ((_ zero_extend 1) #x00000401)
                           ((_ zero_extend 1) #x00000401)))))
      (a!2 (fp.div roundTowardPositive
                   ((_ to_fp_unsigned 8 24)
                     roundTowardPositive
                     (bvsub (select IAXWI81M0B #x00000400) GOH2AHTA2P))
                   (fp #b0 #x7b #b10011001100110011001101))))
(let ((a!3 ((_ fp.to_ubv 32)
             roundTowardZero
             (fp.mul roundTowardPositive
                     a!2
                     (fp.div roundTowardPositive
                             ((_ to_fp_unsigned 8 24)
                               roundTowardPositive
                               G6S8ODQ1ZX)
                             (fp #b0 #x9c #b11011100110101100101000))))))
(let ((a!4 (store IAXWI81M0B
                  (bvadd #x00000401 #x00000001)
                  (bvadd (select IAXWI81M0B (bvadd #x00000401 #x00000001)) a!3))))
(let ((a!5 (ite (bvuge (select a!4 (bvadd #x00000401 #x00000001)) #x3b9aca00)
                #x00000001
                #x00000000)))
  (and (distinct a!1 #b0) (not (distinct a!5 #x00000000))))))))
(assert (let ((a!1 (fp.div roundTowardPositive
                   ((_ to_fp_unsigned 8 24)
                     roundTowardPositive
                     (bvsub (select IAXWI81M0B #x00000400) GOH2AHTA2P))
                   (fp #b0 #x7b #b10011001100110011001101))))
(let ((a!2 ((_ fp.to_ubv 32)
             roundTowardZero
             (fp.mul roundTowardPositive
                     a!1
                     (fp.div roundTowardPositive
                             ((_ to_fp_unsigned 8 24)
                               roundTowardPositive
                               G6S8ODQ1ZX)
                             (fp #b0 #x9c #b11011100110101100101000))))))
(let ((a!3 (store IAXWI81M0B
                  (bvadd #x00000401 #x00000001)
                  (bvadd (select IAXWI81M0B (bvadd #x00000401 #x00000001)) a!2))))
(let ((a!4 (select (store (store (store a!3 #x00000483 #x00000403)
                                 #x00000484
                                 #x00000403)
                          #x00000485
                          (ite EQQ1SQY2AQ #x00000483 #x00000000))
                   #x00000483)))
  (and EQQ1SQY2AQ (bvule a!4 #x00000482)))))))
(assert (let ((a!1 (fp.div roundTowardPositive
                   ((_ to_fp_unsigned 8 24)
                     roundTowardPositive
                     (bvsub (select IAXWI81M0B #x00000400) GOH2AHTA2P))
                   (fp #b0 #x7b #b10011001100110011001101)))
      (a!8 (bvnot ((_ extract 32 32)
                    (bvadd ((_ zero_extend 1) #x00000401)
                           ((_ zero_extend 1) #x00000401))))))
(let ((a!2 ((_ fp.to_ubv 32)
             roundTowardZero
             (fp.mul roundTowardPositive
                     a!1
                     (fp.div roundTowardPositive
                             ((_ to_fp_unsigned 8 24)
                               roundTowardPositive
                               G6S8ODQ1ZX)
                             (fp #b0 #x9c #b11011100110101100101000))))))
(let ((a!3 (store IAXWI81M0B
                  (bvadd #x00000401 #x00000001)
                  (bvadd (select IAXWI81M0B (bvadd #x00000401 #x00000001)) a!2))))
(let ((a!4 (store (store (store a!3 #x00000483 #x00000403)
                         #x00000484
                         #x00000403)
                  #x00000485
                  (ite EQQ1SQY2AQ #x00000483 #x00000000))))
(let ((a!5 ((_ extract 32 32)
             (bvadd ((_ zero_extend 1) (select a!4 #x00000484))
                    ((_ zero_extend 1) (select a!4 #x00000484)))))
      (a!6 (ite (bvult (select a!4 (select a!4 #x00000485))
                       (bvadd (select a!4 #x00000484) #x00000001))
                (bvadd (select a!4 #x00000484) #x00000001)
                (select a!4 (select a!4 #x00000485)))))
(let ((a!7 (bvule (select (store a!4 (select a!4 #x00000485) a!6) #x00000483)
                  #x00000482))
      (a!9 ((_ sign_extend 32)
             (select (store a!4 (select a!4 #x00000485) a!6)
                     (bvadd #x00000401 #x00000000)))))
(let ((a!10 (select (store (store a!4 (select a!4 #x00000485) a!6)
                           (bvadd (select a!4 #x00000484) #x00000000)
                           ((_ extract 31 0) a!9))
                    #x00000483)))
  (and (distinct (select a!4 #x00000484) #x00000000)
       (distinct (bvnot a!5) #b0)
       a!7
       (distinct (bvnot a!5) #b0)
       (distinct a!8 #b0)
       (bvule a!10 #x00000482))))))))))
(assert (let ((a!1 (fp.div roundTowardPositive
                   ((_ to_fp_unsigned 8 24)
                     roundTowardPositive
                     (bvsub (select IAXWI81M0B #x00000400) GOH2AHTA2P))
                   (fp #b0 #x7b #b10011001100110011001101))))
(let ((a!2 ((_ fp.to_ubv 32)
             roundTowardZero
             (fp.mul roundTowardPositive
                     a!1
                     (fp.div roundTowardPositive
                             ((_ to_fp_unsigned 8 24)
                               roundTowardPositive
                               G6S8ODQ1ZX)
                             (fp #b0 #x9c #b11011100110101100101000))))))
(let ((a!3 (store IAXWI81M0B
                  (bvadd #x00000401 #x00000001)
                  (bvadd (select IAXWI81M0B (bvadd #x00000401 #x00000001)) a!2))))
(let ((a!4 (store (store (store a!3 #x00000483 #x00000403)
                         #x00000484
                         #x00000403)
                  #x00000485
                  (ite EQQ1SQY2AQ #x00000483 #x00000000))))
(let ((a!5 (ite (bvult (select a!4 (select a!4 #x00000485))
                       (bvadd (select a!4 #x00000484) #x00000001))
                (bvadd (select a!4 #x00000484) #x00000001)
                (select a!4 (select a!4 #x00000485)))))
(let ((a!6 ((_ sign_extend 32)
             (select (store a!4 (select a!4 #x00000485) a!5)
                     (bvadd #x00000401 #x00000000)))))
(let ((a!7 (store (store a!4 (select a!4 #x00000485) a!5)
                  (bvadd (select a!4 #x00000484) #x00000000)
                  ((_ extract 31 0) a!6))))
(let ((a!8 ((_ extract 32 32)
             (bvadd ((_ zero_extend 1) (select a!7 #x00000484))
                    ((_ zero_extend 1) (select a!7 #x00000484)))))
      (a!9 (ite (bvult (select a!7 (select a!7 #x00000485))
                       (bvadd (select a!7 #x00000484) #x00000001))
                (bvadd (select a!7 #x00000484) #x00000001)
                (select a!7 (select a!7 #x00000485)))))
(let ((a!10 (bvule (select (store a!7 (select a!7 #x00000485) a!9) #x00000483)
                   #x00000482)))
  (and (distinct (select a!7 #x00000484) #x00000000)
       (distinct (bvnot a!8) #b0)
       a!10
       (distinct (bvnot a!8) #b0)
       a!10)))))))))))
(check-sat)
