from ctypes import cdll, POINTER, CFUNCTYPE
from ctypes import c_char_p, c_void_p, c_int32, c_uint32, c_uint64, c_ulong
import os.path

PATHS = [
    './libstp.so',
]

for path in PATHS:
    if not os.path.exists(path):
        continue

    _lib = cdll.LoadLibrary(path)
    break
else:
    raise Exception('Unable to locate the libstp shared object')


def _set_func(name, restype, *argtypes):
    getattr(_lib, name).restype = restype
    getattr(_lib, name).argtypes = argtypes

VC, Expr, Type, WholeCounterExample  = c_void_p, c_void_p, c_void_p, c_void_p

_set_func('vc_createValidityChecker', VC)
_set_func('vc_boolType', Type, VC)
_set_func('vc_arrayType', Type, VC, Type, Type)
_set_func('vc_varExpr', Expr, VC, c_char_p, Type)
_set_func('vc_varExpr1', Expr, VC, c_char_p, c_int32, c_int32)
_set_func('vc_getType', Type, VC, Expr)
_set_func('vc_getBVLength', c_int32, VC, Expr)
_set_func('vc_eqExpr', Expr, VC, Expr, Expr)
_set_func('vc_trueExpr', Expr, VC)
_set_func('vc_falseExpr', Expr, VC)
_set_func('vc_notExpr', Expr, VC, Expr)
_set_func('vc_andExpr', Expr, VC, Expr, Expr)
_set_func('vc_andExprN', Expr, VC, POINTER(Expr), c_int32)
_set_func('vc_orExpr', Expr, VC, Expr, Expr)
_set_func('vc_xorExpr', Expr, VC, Expr, Expr)
_set_func('vc_orExprN', Expr, VC, POINTER(Expr), c_int32)
_set_func('vc_impliesExpr', Expr, VC, Expr, Expr)
_set_func('vc_iffExpr', Expr, VC, Expr, Expr)
_set_func('vc_iteExpr', Expr, VC, Expr, Expr, Expr)
_set_func('vc_boolToBVExpr', Expr, VC, Expr)
_set_func('vc_paramBoolExpr', Expr, VC, Expr, Expr)
_set_func('vc_readExpr', Expr, VC, Expr, Expr)
_set_func('vc_writeExpr', Expr, VC, Expr, Expr, Expr)
_set_func('vc_parseExpr', Expr, VC, c_char_p)
_set_func('vc_printExpr', None, VC, Expr)
_set_func('vc_printExprCCode', None, VC, Expr)
_set_func('vc_printSMTLIB', c_char_p, VC, Expr)
_set_func('vc_printExprFile', None, VC, Expr, c_int32)
_set_func('vc_printExprToBuffer', None, VC, Expr, POINTER(c_char_p), POINTER(c_ulong))
_set_func('vc_printCounterExample', None, VC)
_set_func('vc_printVarDecls', None, VC)
_set_func('vc_clearDecls', None, VC)
_set_func('vc_printAsserts', None, VC, c_int32)
_set_func('vc_printQueryStateToBuffer', None, VC, Expr, POINTER(c_char_p), POINTER(c_ulong), c_int32)
_set_func('vc_printCounterExampleToBuffer', None, VC, POINTER(c_char_p), POINTER(c_ulong))
_set_func('vc_printQuery', None, VC)
_set_func('vc_assertFormula', None, VC, Expr)
_set_func('vc_simplify', Expr, VC, Expr)
_set_func('vc_query_with_timeout', c_int32, VC, Expr, c_int32)
_set_func('vc_query', c_int32, VC, Expr)
_set_func('vc_getCounterExample', Expr, VC, Expr)
_set_func('vc_getCounterExampleArray', None, VC, Expr, POINTER(POINTER(Expr)), POINTER(POINTER(Expr)), POINTER(c_int32))
_set_func('vc_counterexample_size', c_int32, VC)
_set_func('vc_push', None, VC)
_set_func('vc_pop', None, VC)
_set_func('getBVInt', c_int32, Expr)
_set_func('getBVUnsigned', c_uint32, Expr)
_set_func('getBVUnsignedLongLong', c_uint64, Expr)
_set_func('vc_bvType', Type, VC, c_int32)
_set_func('vc_bv32Type', Type, VC)
_set_func('vc_bvConstExprFromDecStr', Expr, VC, c_int32, c_char_p)
_set_func('vc_bvConstExprFromStr', Expr, VC, c_char_p)
_set_func('vc_bvConstExprFromInt', Expr, VC, c_int32, c_uint32)
_set_func('vc_bvConstExprFromLL', Expr, VC, c_int32, c_uint64)
_set_func('vc_bv32ConstExprFromInt', Expr, VC, c_uint32)
_set_func('vc_bvConcatExpr', Expr, VC, Expr, Expr)
_set_func('vc_bvPlusExpr', Expr, VC, c_int32, Expr, Expr)
_set_func('vc_bvPlusExprN', Expr, VC, c_int32, POINTER(Expr), c_int32)
_set_func('vc_bv32PlusExpr', Expr, VC, Expr, Expr)
_set_func('vc_bvMinusExpr', Expr, VC, c_int32, Expr, Expr)
_set_func('vc_bv32MinusExpr', Expr, VC, Expr, Expr)
_set_func('vc_bvMultExpr', Expr, VC, c_int32, Expr, Expr)
_set_func('vc_bv32MultExpr', Expr, VC, Expr, Expr)
_set_func('vc_bvDivExpr', Expr, VC, c_int32, Expr, Expr)
_set_func('vc_bvModExpr', Expr, VC, c_int32, Expr, Expr)
_set_func('vc_sbvDivExpr', Expr, VC, c_int32, Expr, Expr)
_set_func('vc_sbvModExpr', Expr, VC, c_int32, Expr, Expr)
_set_func('vc_sbvRemExpr', Expr, VC, c_int32, Expr, Expr)
_set_func('vc_bvLtExpr', Expr, VC, Expr, Expr)
_set_func('vc_bvLeExpr', Expr, VC, Expr, Expr)
_set_func('vc_bvGtExpr', Expr, VC, Expr, Expr)
_set_func('vc_bvGeExpr', Expr, VC, Expr, Expr)
_set_func('vc_sbvLtExpr', Expr, VC, Expr, Expr)
_set_func('vc_sbvLeExpr', Expr, VC, Expr, Expr)
_set_func('vc_sbvGtExpr', Expr, VC, Expr, Expr)
_set_func('vc_sbvGeExpr', Expr, VC, Expr, Expr)
_set_func('vc_bvUMinusExpr', Expr, VC, Expr)
_set_func('vc_bvAndExpr', Expr, VC, Expr, Expr)
_set_func('vc_bvOrExpr', Expr, VC, Expr, Expr)
_set_func('vc_bvXorExpr', Expr, VC, Expr, Expr)
_set_func('vc_bvNotExpr', Expr, VC, Expr)
_set_func('vc_bvLeftShiftExprExpr', Expr, VC, c_int32, Expr, Expr)
_set_func('vc_bvRightShiftExprExpr', Expr, VC, c_int32,  Expr, Expr)
_set_func('vc_bvSignedRightShiftExprExpr', Expr, VC, c_int32, Expr, Expr)
_set_func('vc_bvLeftShiftExpr', Expr, VC, c_int32, Expr)
_set_func('vc_bvRightShiftExpr', Expr, VC, c_int32, Expr)
_set_func('vc_bv32LeftShiftExpr', Expr, VC, c_int32, Expr)
_set_func('vc_bv32RightShiftExpr', Expr, VC, c_int32, Expr)
_set_func('vc_bvVar32LeftShiftExpr', Expr, VC, Expr, Expr)
_set_func('vc_bvVar32RightShiftExpr', Expr, VC, Expr, Expr)
_set_func('vc_bvVar32DivByPowOfTwoExpr', Expr, VC, Expr, Expr)
_set_func('vc_bvExtract', Expr, VC, Expr, c_int32, c_int32)
_set_func('vc_bvBoolExtract', Expr, VC, Expr, c_int32)
_set_func('vc_bvBoolExtract_Zero', Expr, VC, Expr, c_int32)
_set_func('vc_bvBoolExtract_One', Expr, VC, Expr, c_int32)
_set_func('vc_bvSignExtend', Expr, VC, Expr, c_int32)
_set_func('vc_bvCreateMemoryArray', Expr, VC, c_char_p)
_set_func('vc_bvReadMemoryArray', Expr, VC, Expr, Expr, c_int32)
_set_func('vc_bvWriteToMemoryArray', Expr, VC, Expr, Expr, Expr, c_int32)
_set_func('vc_bv32ConstExprFromInt', Expr, VC, c_uint32)
_set_func('exprString', c_char_p, Expr)
_set_func('typeString', c_char_p, Type)
_set_func('getChild', Expr, Expr, c_int32)
_set_func('vc_isBool', c_int32, Expr)
_set_func('vc_registerErrorHandler', None, CFUNCTYPE(None, c_char_p))
_set_func('vc_getHashQueryStateToBuffer', c_int32, VC, Expr)
_set_func('vc_Destroy', None, VC)
_set_func('vc_DeleteExpr', None, Expr)
_set_func('vc_getWholeCounterExample', WholeCounterExample, VC)
_set_func('vc_getTermFromCounterExample', Expr, VC, Expr, WholeCounterExample)
_set_func('vc_deleteWholeCounterExample', None, WholeCounterExample)
_set_func('getDegree', c_int32, Expr)
_set_func('getBVLength', c_int32, Expr)
_set_func('getVWidth', c_int32, Expr)
_set_func('getIWidth', c_int32, Expr)
_set_func('vc_printCounterExampleFile', None, VC, c_int32)
_set_func('exprName', c_char_p, Expr)
_set_func('getExprID', c_int32, Expr)
_set_func('vc_parseMemExpr', c_int32, VC, c_char_p, POINTER(Expr), POINTER(Expr))
