# - Try to find libcryptominisat4
find_package(PkgConfig)

MACRO(DBG_MSG _MSG)
    # MESSAGE(STATUS "${CMAKE_CURRENT_LIST_FILE}(${CMAKE_CURRENT_LIST_LINE}):\n${_MSG}")
ENDMACRO(DBG_MSG)

SET (CRYPTOMINISAT4_POSSIBLE_ROOT_DIRS
  "${CRYPTOMINISAT4_ROOT_DIR}"
  "$ENV{CRYPTOMINISAT4_ROOT_DIR}"
  "$ENV{CRYPTOMINISAT4_DIR}"
  "$ENV{CRYPTOMINISAT4_HOME}"
  /usr/local
  /usr
  )

FIND_PATH(CRYPTOMINISAT4_ROOT_DIR
  NAMES
  include/cryptominisat4/cryptominisat.h
  PATHS ${CRYPTOMINISAT4_POSSIBLE_ROOT_DIRS}
)
DBG_MSG("CRYPTOMINISAT4_ROOT_DIR=${CRYPTOMINISAT4_ROOT_DIR}")

SET(CRYPTOMINISAT4_INCDIR_SUFFIXES
  include/cryptominisat4
)
DBG_MSG("CRYPTOMINISAT4_INCDIR_SUFFIXES=${CRYPTOMINISAT4_INCDIR_SUFFIXES}")

FIND_PATH(CRYPTOMINISAT4_INCLUDE_DIRS
  NAMES cryptominisat.h
  PATHS ${CRYPTOMINISAT4_ROOT_DIR}
  PATH_SUFFIXES ${CRYPTOMINISAT4_INCDIR_SUFFIXES}
  NO_CMAKE_SYSTEM_PATH
)
DBG_MSG("CRYPTOMINISAT4_INCLUDE_DIRS=${CRYPTOMINISAT4_INCLUDE_DIRS}")

SET(CRYPTOMINISAT4_LIBDIR_SUFFIXES
  lib
)
DBG_MSG("CRYPTOMINISAT4_LIBDIR_SUFFIXES=${CRYPTOMINISAT4_LIBDIR_SUFFIXES}")


find_library(CRYPTOMINISAT4_LIBRARIES
    NAMES cryptominisat4 libcryptominisat4
    PATHS ${CRYPTOMINISAT4_ROOT_DIR}
    PATH_SUFFIXES ${CRYPTOMINISAT4_LIBDIR_SUFFIXES}
)
DBG_MSG("CRYPTOMINISAT4_LIBRARIES=${CRYPTOMINISAT4_LIBRARIES}")

include(FindPackageHandleStandardArgs)
# handle the QUIETLY and REQUIRED arguments and set CRYPTOMINISAT4_FOUND to TRUE
# if all listed variables are TRUE
find_package_handle_standard_args(cryptominisat4  DEFAULT_MSG
                                  CRYPTOMINISAT4_LIBRARIES CRYPTOMINISAT4_INCLUDE_DIRS)
IF (CRYPTOMINISAT4_INCLUDE_DIRS AND CRYPTOMINISAT4_LIBRARIES)
    SET(CRYPTOMINISAT4_FOUND TRUE)
endif (CRYPTOMINISAT4_INCLUDE_DIRS AND CRYPTOMINISAT4_LIBRARIES)

mark_as_advanced(CRYPTOMINISAT4_INCLUDE_DIRS CRYPTOMINISAT4_LIBRARIES )
