# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/stable/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

# Capitalised to match the name the website shows under the logo.
project = 'STP'
copyright = '2018-2026, The STP Project'
author = 'The STP Project'

# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = '2.4.1'


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', '.direnv', 'requirements.txt']

# The name of the Pygments (syntax highlighting) style to use. 'friendly' sits
# better on the cream page background than the default white-backed 'sphinx'.
pygments_style = 'friendly'


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

# This directory is the whole of stp.github.io/stp/ -- landing page and manual
# together. The options below carry over the look of the Jekyll site that used
# to serve the landing page: the cream page, the red links, Vollkorn, and the
# round logo in the sidebar.
html_theme_options = {
    'logo': 'logo.png',
    'logo_name': True,
    'logo_text_align': 'center',
    'description': 'The Simple Theorem Prover',
    'description_font_style': 'normal',

    'font_family': "'Vollkorn', Georgia, serif",
    'head_font_family': "'Vollkorn', Georgia, serif",

    'base_bg': '#F1EED9',
    'body_bg': '#F1EED9',
    'base_text': '#46433A',
    'body_text': '#46433A',
    'link': '#CE534D',
    'link_hover': '#CE534D',
    'sidebar_header': '#46433A',
    'sidebar_text': '#46433A',
    'sidebar_link': '#CE534D',
    'sidebar_list': '#46433A',
    'sidebar_search_button': '#C9C3A4',
    'footer_text': '#8C8879',
    'hr_border': '#C9C3A4',
    'anchor': '#C9C3A4',

    # Code needs to read as code without a white slab on the cream page.
    'code_bg': '#E7E2C6',
    'pre_bg': '#E7E2C6',
    'code_text': '#46433A',
    'code_hover': '#DCD6B6',
    'highlight_bg': '#E7E2C6',

    'show_powered_by': False,
    'show_relbars': False,
    'sidebar_collapse': False,
    'page_width': '940px',
    'sidebar_width': '240px',

    'extra_nav_links': {
        'Source code on GitHub': 'https://github.com/stp/stp',
    },
}

html_static_path = ['_static']

html_favicon = '_static/favicon.ico'

# Shown in the browser tab and in the sidebar's alt text, in place of the
# default "STP 2.4.1 documentation".
html_title = 'STP, the Simple Theorem Prover'
html_short_title = 'STP'

# Used for the canonical link, and for the Open Graph URLs that
# _templates/layout.html emits.
html_baseurl = 'https://stp.github.io/stp/'

html_context = {
    'og_image': html_baseurl + '_static/logo.png',
}

# Files copied verbatim into the build. _extra/docs holds one redirect stub per
# page for /stp/docs/, where the manual was published before the landing page
# and the manual were merged into this one Sphinx build.
html_extra_path = ['_extra']

# Vollkorn is the site's body font; custom.css carries the handful of rules
# the theme options cannot express (the ring around the logo, link underlining
# on hover only, the faded rule).
html_css_files = [
    'https://fonts.googleapis.com/css?family=Vollkorn',
    'custom.css',
]

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
html_sidebars = {
    '**': ['about.html', 'navigation.html', 'searchfield.html'],
}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'stpdoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'stp.tex', 'stp Documentation',
     'The STP Project', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'stp', 'stp Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'stp', 'stp Documentation',
     author, 'stp', 'One line description of project.',
     'Miscellaneous'),
]
