"""pip-install bindings/python on its own and import it against a built libstp.

Usage: pip_install_test.py <bindings/python source dir> <libstp> <scratch dir>

Exits 77, which ctest reports as skipped, when this interpreter cannot build
the package offline: no pip, or a setuptools older than pyproject.toml needs.
"""

import os
import shutil
import subprocess
import sys

SKIP = 77

QUERY = """
import stp
s = stp.Solver()
x = s.bitvec('x', width=8)
s.add(x + x != 2 * x)
assert s.check() is False, 'pip-installed module gave the wrong answer'
print(stp.get_lib()._name)
"""


def main():
    source, libstp, scratch = sys.argv[1:4]
    libstp = os.path.abspath(libstp)

    try:
        # setuptools first: pip imports the standard library's distutils,
        # which setuptools' distutils shim then refuses.
        import setuptools
        import pip  # noqa: F401
    except ImportError as e:
        print('skipped: %s' % e)
        return SKIP
    if int(setuptools.__version__.split('.')[0]) < 61:
        print('skipped: setuptools %s predates pyproject metadata'
              % setuptools.__version__)
        return SKIP

    # A copy, because pip builds in place and would leave build/ and
    # stp.egg-info in the checkout.
    shutil.rmtree(scratch, ignore_errors=True)
    src = os.path.join(scratch, 'src')
    site = os.path.join(scratch, 'site')
    shutil.copytree(source, src)

    subprocess.check_call(
        [sys.executable, '-m', 'pip', 'install', '--no-build-isolation',
         '--no-deps', '--no-index', '--disable-pip-version-check',
         '--target', site, src])

    with open(os.path.join(site, 'stp', 'library_path.py')) as f:
        if 'PATHS = []' not in f.read():
            print('pip installed a library_path.py generated by CMake')
            return 1

    base_env = dict(os.environ)
    for var in ('STP_LIBRARY', 'LD_LIBRARY_PATH', 'DYLD_LIBRARY_PATH'):
        base_env.pop(var, None)
    base_env['PYTHONPATH'] = site

    def run(extra):
        env = dict(base_env, **extra)
        out = subprocess.check_output([sys.executable, '-c', QUERY],
                                      env=env, cwd=scratch)
        return out.decode().strip()

    # STP_LIBRARY names the library outright.
    loaded = run({'STP_LIBRARY': libstp})
    if os.path.abspath(loaded) != libstp:
        print('STP_LIBRARY=%s, but loaded %s' % (libstp, loaded))
        return 1
    print('ok: STP_LIBRARY')

    # And the search path variable, given only the directory. It has to win
    # over a libstp installed system-wide, which ldconfig would find first.
    if sys.platform.startswith('linux'):
        loaded = run({'LD_LIBRARY_PATH': os.path.dirname(libstp)})
        if os.path.dirname(os.path.abspath(loaded)) != os.path.dirname(libstp):
            print('LD_LIBRARY_PATH=%s, but loaded %s'
                  % (os.path.dirname(libstp), loaded))
            return 1
        print('ok: LD_LIBRARY_PATH')
    return 0


if __name__ == '__main__':
    sys.exit(main())
